name: Publish Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 1'
  pull_request:

env:
  LIBJXL_VERSION: v0.10.3
  IMAGEMAGICK_VERSION: '7.1.1-36'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_branch:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.6.1
        with:
          build-args: GIT_TAG=${{ env.LIBJXL_VERSION }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/cmahnke/jpeg-xl-action:latest
            ghcr.io/cmahnke/jpeg-xl-action:${{ env.LIBJXL_VERSION }}

  imagemagick:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: main_branch
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.6.1
        with:
          build-args: IMAGEMAGICK_GIT_TAG=${{ env.IMAGEMAGICK_VERSION }}
          push: true
          file: docker/imagemagick/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/cmahnke/jpeg-xl-action/imagemagick:latest
            ghcr.io/cmahnke/jpeg-xl-action/imagemagick:${{ env.IMAGEMAGICK_VERSION }}
