name: Publish Docker image
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * 1'

jobs:
  main_branch:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          tags: |
            ghcr.io/cmahnke/jpeg-xl-action:latest

  latest-release:
    name: Push Docker image Version 0.3.7 to GitHub Packages
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: GIT_TAG=v0.3.7
          push: true
          tags: |
            ghcr.io/cmahnke/jpeg-xl-action:0.3.7
